import { HttpClient } from '@angular/common/http';
import { Injectable, inject, isDevMode } from '@angular/core'; // Added isDevMode
import { lastValueFrom } from 'rxjs';
import { validateUrl } from '../utils/url-validator'; // Import the validator

interface AppEnvConfig {
    BACKEND_URL: string;
}

// Default URL if config.json fails or running in a context where it's not provided by Docker.
// This should ideally match your local development backend.
const DEFAULT_DEV_BACKEND_URL = 'http://localhost:3333';
const SAFE_FALLBACK_URL = 'http://localhost:3333'; // Fallback if validation fails severely

@Injectable({
    providedIn: 'root',
})
export class AppConfigService {
    private http = inject(HttpClient);
    private appConfig: AppEnvConfig | null = null;

    async loadAppConfig(): Promise<void> {
        let loadedConfig: AppEnvConfig | null = null;
        try {
            // In a deployed Docker environment, /assets/config.json will be generated by entrypoint.sh
            // For local development, you can place a config.json in src/assets for testing,
            // or it will fall back to DEFAULT_DEV_BACKEND_URL.
            loadedConfig = await lastValueFrom(this.http.get<AppEnvConfig>('/assets/config.json'));
            console.log('App config loaded from /assets/config.json:', loadedConfig);
        } catch (error) {
            console.warn('Failed to load /assets/config.json. Using default development backend URL as initial value.', error);
            loadedConfig = { BACKEND_URL: DEFAULT_DEV_BACKEND_URL };
        }

        if (loadedConfig && loadedConfig.BACKEND_URL) {
            const isProductionEnv = !isDevMode();
            if (validateUrl(loadedConfig.BACKEND_URL, isProductionEnv)) {
                this.appConfig = loadedConfig;
            } else {
                // Validation failed, log and use a safe fallback or throw critical error
                console.error(
                    `BACKEND_URL "${loadedConfig.BACKEND_URL}" from config.json failed validation. ` +
                    `isProduction: ${isProductionEnv}. Falling back to SAFE_FALLBACK_URL: ${SAFE_FALLBACK_URL}`
                );
                // Depending on policy, you might throw an error here to halt app initialization
                // throw new Error("Invalid BACKEND_URL configuration after loading config.json");
                this.appConfig = { BACKEND_URL: SAFE_FALLBACK_URL };
            }
        } else {
            // loadedConfig is null or BACKEND_URL is missing
            console.error('BACKEND_URL missing in loaded config or config itself is null. Using SAFE_FALLBACK_URL.');
            this.appConfig = { BACKEND_URL: SAFE_FALLBACK_URL };
        }
    }

    getBackendUrl(): string {
        if (!this.appConfig) {
            // This case should ideally not happen if APP_INITIALIZER waits for loadAppConfig
            console.warn('App config not loaded at time of getBackendUrl() call. This might indicate an APP_INITIALIZER issue. Returning SAFE_FALLBACK_URL.');
            return SAFE_FALLBACK_URL;
        }
        return this.appConfig.BACKEND_URL || SAFE_FALLBACK_URL; // Ensure fallback if property is somehow empty
    }
}
